version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend-container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend/coffees-front
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: coffee_db
      POSTGRES_USER: coffee_admin
      POSTGRES_PASSWORD: coffee_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      
volumes:
  db_data:


