# Generated by Django 5.2 on 2026-05-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('altitude_min', models.PositiveBigIntegerField(blank=True, help_text='Altitud mínima de cultivo en metros', null=True)),
                ('altitude_max', models.PositiveBigIntegerField(blank=True, help_text='Altitud máxima de cultivo en metros', null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['name'], 'verbose_name_plural': 'Coffees'},
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='roast_level',
        ),
        migrations.AddField(
            model_name='coffee',
            name='brew_temp_celsius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Temperatura de extracción recomendada en °C', null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='grind_size',
            field=models.CharField(blank=True, help_text='Ej: Fine, Medium-Coarse', max_length=100),
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='recommended_brew',
            field=models.CharField(blank=True, help_text='Ej: Chemex, Espresso, French Press', max_length=200),
        ),
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coffee',
            name='weight_grams',
            field=models.PositiveIntegerField(default=250, help_text='Peso del paquete en gramos'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='coffees.origin'),
        ),
    ]
